### ISSUE TITLE
Identify blockers for the RayWenderlich article.

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/gradle-dependencies-plugins#142]
This is the project used for the ray wenderlich article

https://github.com/jmfayard/update-legacy-android-project/branches/all

**Comment by jmfayard** [comment]
Current issues in the `louiscad`  branch

- `refrshVersions` removes the `plugin.android` property that is necessary for the build sync
- some dependencies are commented in `app/build.gradle` because they cannot be resolved for some reasons....
- auto-complete does not work
- maybe related: the build scan does not find the plugins versions https://scans.gradle.com/s/sdowgzarco3jg/plugins

**Comment by LouisCAD** [comment]
Now that I published version 0.5.0 of the dependencies plugin, I'm updating Splitties Gradle plugin and looking into this issue.

**Comment by LouisCAD** [comment]
I submitted [a PR](https://github.com/jmfayard/update-legacy-android-project/pull/2) that fixes these issues you mentioned:
- some dependencies are commented in `app/build.gradle` because they cannot be resolved for some reasons....
- auto-complete does not work

Can you make a build scan again and see if there's still not found plugins versions?

About the first issue, it's a bug that I'll need to fix, it's in issue #144.

**Comment by LouisCAD** [comment]
#144 is now resolved, closing this issue.
